# docker-compose file for starting a nextcloud instance.
# Copyright Abigail Schubert 2020
# This work is licensed under the terms of the GNU General Public License v3
# For a copy, see <https://www.gnu.org/licenses/>

version: "3.6"

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin --binlog-format=ROW
    restart: always
    healthcheck:
      # Healthcheck from Nicolas Kuttler
      # https://kuttler.eu/code/docker-compose-mariadb-mysql-healthcheck/
      #  test: "echo hi"
      test: "mysql -u $${MYSQL_USER} -p$${MYSQL_PASSWORD}
             --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./_secrets_mysql.txt
    environment:
      MYSQL_DATABASE: "nextcloud"

  app:
    build: ./app
    ports:
      - 8080:80
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /media/pleiades/nextcloud:/media/data
    env_file:
      - ./_secrets_nextcloud.txt
    environment:
      NEXTCLOUD_DATA_DIR: /media/data
      MYSQL_HOST: db
      MYSQL_DATABASE: "nextcloud"

